// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEncryptedBackup(arg1) {
  return window['go']['main']['App']['CreateEncryptedBackup'](arg1);
}

export function DeleteReport(arg1) {
  return window['go']['main']['App']['DeleteReport'](arg1);
}

export function ListReports() {
  return window['go']['main']['App']['ListReports']();
}

export function OpenPocFile(arg1) {
  return window['go']['main']['App']['OpenPocFile'](arg1);
}

export function RestoreEncryptedBackup(arg1, arg2) {
  return window['go']['main']['App']['RestoreEncryptedBackup'](arg1, arg2);
}

export function SaveReport(arg1) {
  return window['go']['main']['App']['SaveReport'](arg1);
}

export function StorePath() {
  return window['go']['main']['App']['StorePath']();
}
