// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteReport(arg1:string):Promise<void>;

export function ListReports():Promise<Array<main.Report>>;

export function OpenPocFile(arg1:main.PocFile):Promise<string>;

export function SaveReport(arg1:main.ReportDraft):Promise<main.Report>;

export function StorePath():Promise<string>;
